---
- name: Configure Monitor Node
  hosts: monitor_node
  become: yes
  roles:
    - docker
  tasks:
    - name: Create Config directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/prometheus
        - /etc/grafana/provisioning/datasources
        - /etc/grafana/provisioning/dashboards
        - /var/lib/grafana/dashboards

    - name: Setup Prometheus Configuration
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml

    - name: Copy Grafana Provisioning files
      copy:
        src: "{{ playbook_dir }}/ansible/files/{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: 'datasource.yml', dest: '/etc/grafana/provisioning/datasources/' }
        - { src: 'grafana/dashboards.yml', dest: '/etc/grafana/provisioning/dashboards/' }
        - { src: 'grafana/dashboards/node-exporter.json', dest: '/var/lib/grafana/dashboards/' }

    - name: Deploy Prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus:latest
        state: started
        restart_policy: always
        volumes:
          - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - "9090:9090"

    - name: Deploy Grafana
      docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: always
        user: "0" # Щоб уникнути проблем з правами на папки
        volumes:
          - /etc/grafana/provisioning:/etc/grafana/provisioning
          - /var/lib/grafana/dashboards:/var/lib/grafana/dashboards
        ports:
          - "3000:3000"
